apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config
data:
  init.sql: |          
      CREATE DATABASE kong
          WITH
          OWNER = postgres
          ENCODING = 'UTF8'
          LC_COLLATE = 'en_US.utf8'
          LC_CTYPE = 'en_US.utf8'
          TABLESPACE = pg_default
          CONNECTION LIMIT = -1
          IS_TEMPLATE = False;	

      CREATE DATABASE keycloak
          WITH
          OWNER = postgres
          ENCODING = 'UTF8'
          LC_COLLATE = 'en_US.utf8'
          LC_CTYPE = 'en_US.utf8'
          TABLESPACE = pg_default
          CONNECTION LIMIT = -1
          IS_TEMPLATE = False;	

      CREATE DATABASE konga
          WITH
          OWNER = postgres
          ENCODING = 'UTF8'
          LC_COLLATE = 'en_US.utf8'
          LC_CTYPE = 'en_US.utf8'
          TABLESPACE = pg_default
          CONNECTION LIMIT = -1
          IS_TEMPLATE = False;	

      CREATE DATABASE funcionarios
          WITH
          OWNER = postgres
          ENCODING = 'UTF8'
          LC_COLLATE = 'en_US.utf8'
          LC_CTYPE = 'en_US.utf8'
          TABLESPACE = pg_default
          CONNECTION LIMIT = -1
          IS_TEMPLATE = False;
          