apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.37
        ports: 
        - containerPort: 14268
          name: httpthrift
        - containerPort: 6831
          name: udpthrift
        - containerPort: 16686
          name: apiui
        imagePullPolicy: IfNotPresent
        envFrom: 
          - configMapRef: 
              name: jaeger-config
