version: '3.4'

services:
  cadastro.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Keycloak
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 56701:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  cadastro.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Keycloak
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 56702:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  cadastro.workerservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
