version: '3.4'

services:
  cadastro.api:
    image: ${DOCKER_REGISTRY-}cadastroapi
    container_name: cadastro.api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    networks:
      - externo

  cadastro.mvc:
    image: ${DOCKER_REGISTRY-}cadastromvc
    container_name: cadastro.mvc
    build:
      context: .
      dockerfile: src/MVC/Dockerfile
    networks:
      - externo

  db:
    image: postgres:13.3-alpine
    container_name: db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db01
    # Un-comment to access the db service directly
    ports:
     - 5432:5432
    networks:
      - base
    restart: unless-stopped
    volumes:
      - dbData:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    container_name: keycloak
    environment:
      - DB_VENDOR=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_ADDR=db
      - DB_DATABASE=db01
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=./realm-export.json
    volumes:
      - ./src/KeyCloak/realm-export.json:/realm-export.json
    depends_on:
      - db
      #- nginx
    networks:
      - base
      - externo
    ports:
      - 8088:8080
      - 9099:9090
  angular:
    image: angularkeycloak
    container_name: angular
    build:
      context: ./src/angular/
      dockerfile: Dockerfile
    depends_on:
      - cadastro.api
    networks:
      - externo
    ports:
      - 4200:80

  nginx:
    image: nginx:1.21.0-alpine
    container_name: nginx
    volumes:
       - ./src/KeyCloak/nginx.conf:/etc/nginx/nginx.conf
       - ./src/KeyCloak/nginxconfig:/etc/nginx/conf.d/
    ports:
       - 80:80
       - 90:90
    networks:
      - externo
    depends_on:
      - fusionauth
      - cadastro.mvc
      - angular      
      - cadastro.api      
      - keycloak


  fusionauth:
    image: fusionauth/fusionauth-app:1.26.1
    container_name: fusionauth
    depends_on:
      - db
    environment:
        DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
        # Prior to version 1.19.0, use this deprecated name
        # DATABASE_ROOT_USER: ${POSTGRES_USER}
        DATABASE_ROOT_USERNAME: postgres
        DATABASE_ROOT_PASSWORD: postgres
        # Prior to version 1.19.0, use this deprecated name
        # DATABASE_USER: ${DATABASE_USER}
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: postgres
        # Prior to version 1.19.0, use this deprecated names
        # FUSIONAUTH_MEMORY: ${FUSIONAUTH_MEMORY}
        # FUSIONAUTH_SEARCH_ENGINE_TYPE: database
        # FUSIONAUTH_URL: http://fusionauth:9011
        # FUSIONAUTH_RUNTIME_MODE: development
        FUSIONAUTH_APP_MEMORY: 512M
        FUSIONAUTH_APP_RUNTIME_MODE: development
        FUSIONAUTH_APP_URL: http://fusionauth:9011
        SEARCH_TYPE: database
    networks:
      - externo
      - base
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config


networks:
  base:
  externo:
volumes:
  dbData:
  dbLog:
  dbSecrets:
  fa_config:
