version: '3.4'

services:
  cadastro.api:
    image: ${DOCKER_REGISTRY-}cadastroapi
    build:
      context: .
      dockerfile: src/API/Dockerfile
    networks:
      - externo

  cadastro.mvc:
    image: ${DOCKER_REGISTRY-}cadastromvc
    build:
      context: .
      dockerfile: src/MVC/Dockerfile
    networks:
      - externo

  db:
    image: postgres:13.3-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db01
    # Un-comment to access the db service directly
    ports:
     - 5432:5432
    networks:
      - base
    restart: unless-stopped
    volumes:
      - dbData:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    container_name: sampleKeycloak
    environment:
      - DB_VENDOR=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_ADDR=db
      - DB_DATABASE=db01
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=./realm-export.json
    volumes:
      - ./src/KeyCloak/realm-export.json:/realm-export.json
    depends_on:
      - db
      #- nginx
    networks:
      - base
      - externo
    ports:
      - 8088:8080
      - 9099:9090
  angular:
    image: angularkeycloak
    build:
      context: ./src/angular/
      dockerfile: Dockerfile
    container_name: angularkeycloak
    depends_on:
      - cadastro.api
    networks:
      - externo
    ports:
      - 4200:80

  nginx:
    image: nginx:1.21.0-alpine
    volumes:
       - ./src/KeyCloak/nginx.conf:/etc/nginx/nginx.conf
       - ./src/KeyCloak/nginxconfig:/etc/nginx/conf.d/
    ports:
       - "80:80"
       - "90:90"
    networks:
      - externo


networks:
  base:
  externo:
volumes:
  dbData:
  dbLog:
  dbSecrets:
