apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
   path: /volumes/
