metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

# metricbeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: elasticsearch
  metricsets:
    - node
    - node_stats
    - cluster_stats
    - index
  enabled: true  
  hosts: ["elasticsearch:9200"] 

- module: nginx
  metricsets: ["stubstatus"]
  enabled: true
  period: 10s
  # Nginx hosts
  hosts: ["http://nginx"]
  # Path to server status. Default nginx_status
  server_status_path: "metrics"

- module: rabbitmq
  metricsets: ["node", "queue", "connection", "exchange"]
  enabled: true
  period: 10s
  hosts: ["rabbitmq:15672"]
  username: mc
  password: mc2

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]


setup.kibana:
  host: "kibana:5601"


setup.dashboards.enabled: true