version: "3"
services:
  # proxy:
  #   image: nginx:1.19.5
  #   container_name: sampleKeycloakNginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx/api.conf:/etc/nginx/conf.d/api.conf
  #     - ./nginx/mvc.conf:/etc/nginx/conf.d/mvc.conf
  #     - ./nginx/keycloak.conf:/etc/nginx/conf.d/keycloak.conf
  #   networks:
  #     - base
  #     - externo
  #   ports:
  #     - 80:80
  #     - 8081:8081
  #     - 8088:8088
  #     - 8085:8085
  #   depends_on:
  #     - mvc
  #     - api
  #     - keycloak
  db:
    image: correia97/mssql-server-linux:2019-latest
    container_name: sampleKeycloakDB
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=Mudar12345
      - MSSQL_DATABASE=db01
      - MSSQL_DATABASE_COLLATE=SQL_Latin1_General_CP1_CI_AI
      - MSSQL_USER=myUser
      - MSSQL_PASSWORD=myPa55W0d
    volumes:
      - dbData:/var/opt/mssql/data
      - dbLog:/var/opt/mssql/log
      - dbSecrets:/var/opt/mssql/secrets
    networks:
      - base
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.1
    container_name: sampleKeycloak
    environment:
      - DB_VENDOR=mssql
      - DB_USER=myUser
      - DB_PASSWORD=myPa55W0d
      - DB_ADDR=db
      - DB_DATABASE=db01
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=./realm-export.json
    volumes:
      - ./realm-export.json:/realm-export.json
    depends_on:
      - db
    networks:
      - base
      - externo
    ports:
      - 8088:8080
      - 9099:9090
  api:
    image: api
    build:
      context: API/
      dockerfile: Dockerfile
    container_name: sampleKeycloakAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BaseAuthUrl=http://192.168.0.142:8088
    depends_on:
      - db
    networks:
      - base
      - externo
    ports:
      - 8081:80
  mvc:
    image: mvc
    build:
      context: MVC/
      dockerfile: Dockerfile
    container_name: sampleKeycloakMVC
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BaseAuthUrl=http://192.168.0.142:8088
    depends_on:
      - api
    networks:
      - externo
    ports:
      - 8085:80
  angular:
    image: angularkeycloak
    build:
      context: angularkeycloakprotect/
      dockerfile: Dockerfile
    container_name: angularkeycloak
    depends_on:
      - api
    networks:
      - externo
    ports:
      - 4200:80

networks:
  base:
    driver: overlay
  externo:
    driver: overlay
volumes:
  dbData:
  dbLog:
  dbSecrets:
